USE database_schema;

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM ability WHERE TRUE;
DELETE FROM account_ WHERE TRUE;
DELETE FROM account_approve_test_score WHERE TRUE;
DELETE FROM account_bookmark_status WHERE TRUE;
DELETE FROM account_comment_status WHERE TRUE;
DELETE FROM account_has_location WHERE TRUE;
DELETE FROM account_has_media WHERE TRUE;
DELETE FROM account_like_status WHERE TRUE;
DELETE FROM account_manage_group WHERE TRUE;
DELETE FROM app_language WHERE TRUE;
DELETE FROM certificate WHERE TRUE;
DELETE FROM company WHERE TRUE;
DELETE FROM connect WHERE TRUE;
DELETE FROM content WHERE TRUE;
DELETE FROM course WHERE TRUE;
DELETE FROM event_ WHERE TRUE;
DELETE FROM group_ WHERE TRUE;
DELETE FROM image WHERE TRUE;
DELETE FROM instructor WHERE TRUE;
DELETE FROM instructor_teaches_course WHERE TRUE;
DELETE FROM job_offer WHERE TRUE;
DELETE FROM location WHERE TRUE;
DELETE FROM media WHERE TRUE;
DELETE FROM message WHERE TRUE;
DELETE FROM normal WHERE TRUE;
DELETE FROM project WHERE TRUE;
DELETE FROM share_in_group WHERE TRUE;
DELETE FROM status_ WHERE TRUE;
DELETE FROM student WHERE TRUE;
DELETE FROM student_takes_course WHERE TRUE;
DELETE FROM test_score WHERE TRUE;
DELETE FROM user_ WHERE TRUE;
DELETE FROM user_apply_job WHERE TRUE;
DELETE FROM user_has_certificate WHERE TRUE;
DELETE FROM user_makes_project WHERE TRUE;
DELETE FROM video WHERE TRUE;
DELETE FROM view_profile WHERE TRUE;

DROP TABLE ability;
DROP TABLE account_;
DROP TABLE account_approve_test_score;
DROP TABLE account_bookmark_status;
DROP TABLE account_comment_status;
DROP TABLE account_has_location;
DROP TABLE account_has_media;
DROP TABLE account_like_status;
DROP TABLE account_manage_group;
DROP TABLE app_language;
DROP TABLE certificate;
DROP TABLE company;
DROP TABLE connect;
DROP TABLE content;
DROP TABLE course;
DROP TABLE event_;
DROP TABLE group_;
DROP TABLE image;
DROP TABLE instructor;
DROP TABLE instructor_teaches_course;
DROP TABLE job_offer;
DROP TABLE location;
DROP TABLE media;
DROP TABLE message;
DROP TABLE normal;
DROP TABLE project;
DROP TABLE share_in_group;
DROP TABLE status_;
DROP TABLE student;
DROP TABLE student_takes_course;
DROP TABLE test_score;
DROP TABLE user_;
DROP TABLE user_apply_job;
DROP TABLE user_has_certificate;
DROP TABLE user_makes_project;
DROP TABLE video;
DROP TABLE view_profile;

DROP DATABASE database_schema;

SET FOREIGN_KEY_CHECKS = 1;